--- 
results_location: ../etc/runs/
project_id: phileas-1351
dataset: cloud
email_recipients:
  - d.kheyman@gmail.com
  - rashimgreat@gmail.com
email_from: rbcphileas@gmail.com
test_suite:
  - cloud: AWS
    globals:
      image: ami-9f086de0
      machine_type: r4.4xlarge
      default_timeout: 600
      zones: us-east-1
    tests:
      - test: iperf
        options:
          iperf_runtime_in_seconds: 30
      - test: fio
        options:
          fio_jobfile: ../lib/providers/AWS/config/fio.txt
      - test: coremark
      - test: ping
      - test: unixbench
  - cloud: GCP
    globals:
      image_project: ubuntu-os-cloud
      image_family: ubuntu-1604-lts
      machine_type:
        cpus: 20
        memory: 130GiB
      zones: us-east1-b
    tests:
      - test: iperf
        options:
          iperf_runtime_in_seconds: 30
      - test: fio
        options:
          fio_jobfile: ../lib/providers/GCP/config/fio.txt
      - test: coremark
      - test: ping
      - test: unixbench
        options:
          unixbench_all_cores: True
  - cloud: Rackspace
    globals:
      # rack_path: ../lib/providers/Rackspace/rack
      rackspace_region: IAD
      rack_profile: phileas
      machine_type: Memory1-120
      rackspace_boot_from_cbs_volume: True
    tests:
      - test: iperf
        options:
          iperf_runtime_in_seconds: 30
      - test: fio
        options:
          fio_jobfile: ../lib/providers/Rackspace/config/fio.txt
      - test: coremark
      - test: ping
      - test: unixbench
  - cloud: Azure
    globals:
      machine_type: Standard_E16_v3
      zones: eastus
    tests:
      - test: iperf
        options:
          iperf_runtime_in_seconds: 30
      - test: fio
        options:
          fio_jobfile: ../lib/providers/Azure/config/fio.txt
      - test: coremark
      - test: ping
      - test: unixbench
  - cloud: AliCloud
    globals:
        aliyuncli_path: aliyun
        zones: us-east-1a
        machine_type: ecs.r5.4xlarge
        ali_system_disk_type: cloud_ssd
    tests:
      - test: iperf
        options:
          iperf_runtime_in_seconds: 30
      - test: fio
        options:
          fio_jobfile: ../lib/providers/AliCloud/config/fio.txt
      - test: coremark
      - test: ping
      - test: unixbench
